Add minimalist test script and wokflow step

diff --git a/.github/workflows/whatsapp-server.yml b/.github/workflows/whatsapp-server.yml
--- a/.github/workflows/whatsapp-server.yml
+++ b/.github/workflows/whatsapp-server.yml
@@ -47,6 +47,27 @@ jobs:
           docker build -f $DOCKERFILE_DIR/Dockerfile \
             -t $ECR_REPO_URL:latest .
 
+      - name: Run pytest tests inside Docker container
+        run: |
+          CONTAINER_ID=$(docker run -d -v $PWD:/results $ECR_REPO_URL:latest)
+          docker exec $CONTAINER_ID python3 -m pytest -v -s /whatsapp-server-template/tests/ --junitxml=/results/test-results-1.xml
+          TEST_RESULT=$?
+          docker stop $CONTAINER_ID
+          exit $TEST_RESULT
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results-1
+          path: test-results-1.xml
+
+      - name: Fail job if tests failed
+        if: steps.run-tests.outcome == 'failure'
+        run: |
+          echo "Tests failed"
+          exit 1
+
 
   deploy-whatsapp-server:
     runs-on: ubuntu-latest
